Update env.yml

diff --git a/.github/workflows/env.yml b/.github/workflows/env.yml
--- a/.github/workflows/env.yml
+++ b/.github/workflows/env.yml
@@ -1,4 +1,4 @@
-name: env_Check
+name: Env Check
 
 on: [push, pull_request]
 
@@ -6,12 +6,14 @@ jobs:
   check-env:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - run: | 
-        if git ls-files | grep '\.env'; then
-          echo "Error : .env file found in repository"
-          exit 1
-        else
-          echo "No .env files found"
-        fi
-      
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Check for .env files
+        run: |
+          if git ls-files | grep '\.env'; then
+            echo "Error: .env file found in repository"
+            exit 1
+          else
+            echo "No .env files found"
+          fi
